package com.gyf.szcrm.mapper;

import com.gyf.szcrm.model.CourseCategory;

import java.util.List;

public interface CourseCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_category
     *
     * @mbggenerated Mon Sep 21 22:16:00 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_category
     *
     * @mbggenerated Mon Sep 21 22:16:00 CST 2020
     */
    int insert(CourseCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_category
     *
     * @mbggenerated Mon Sep 21 22:16:00 CST 2020
     */
    int insertSelective(CourseCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_category
     *
     * @mbggenerated Mon Sep 21 22:16:00 CST 2020
     */
    CourseCategory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_category
     *
     * @mbggenerated Mon Sep 21 22:16:00 CST 2020
     */
    int updateByPrimaryKeySelective(CourseCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_category
     *
     * @mbggenerated Mon Sep 21 22:16:00 CST 2020
     */
    int updateByPrimaryKey(CourseCategory record);

    List<CourseCategory> findAllList();
}