package com.gyf.szcrm.model;

import java.util.Date;

public class CourseOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_order.uuid
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_order.order_id
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_order.wechat_no
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    private String wechatNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_order.wechat_mark
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    private String wechatMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_order.qq_no
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    private String qqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_order.tel
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_order.course_name
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    private String courseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_order.course_price
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    private String coursePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_order.order_date
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    private Date orderDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_order.update_datetime
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    private Date updateDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_order.name
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_order.remark
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_order.uuid
     *
     * @return the value of t_course_order.uuid
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_order.uuid
     *
     * @param uuid the value for t_course_order.uuid
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_order.order_id
     *
     * @return the value of t_course_order.order_id
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_order.order_id
     *
     * @param orderId the value for t_course_order.order_id
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_order.wechat_no
     *
     * @return the value of t_course_order.wechat_no
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    public String getWechatNo() {
        return wechatNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_order.wechat_no
     *
     * @param wechatNo the value for t_course_order.wechat_no
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    public void setWechatNo(String wechatNo) {
        this.wechatNo = wechatNo == null ? null : wechatNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_order.wechat_mark
     *
     * @return the value of t_course_order.wechat_mark
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    public String getWechatMark() {
        return wechatMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_order.wechat_mark
     *
     * @param wechatMark the value for t_course_order.wechat_mark
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    public void setWechatMark(String wechatMark) {
        this.wechatMark = wechatMark == null ? null : wechatMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_order.qq_no
     *
     * @return the value of t_course_order.qq_no
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    public String getQqNo() {
        return qqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_order.qq_no
     *
     * @param qqNo the value for t_course_order.qq_no
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    public void setQqNo(String qqNo) {
        this.qqNo = qqNo == null ? null : qqNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_order.tel
     *
     * @return the value of t_course_order.tel
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_order.tel
     *
     * @param tel the value for t_course_order.tel
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_order.course_name
     *
     * @return the value of t_course_order.course_name
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_order.course_name
     *
     * @param courseName the value for t_course_order.course_name
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_order.course_price
     *
     * @return the value of t_course_order.course_price
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    public String getCoursePrice() {
        return coursePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_order.course_price
     *
     * @param coursePrice the value for t_course_order.course_price
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    public void setCoursePrice(String coursePrice) {
        this.coursePrice = coursePrice == null ? null : coursePrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_order.order_date
     *
     * @return the value of t_course_order.order_date
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_order.order_date
     *
     * @param orderDate the value for t_course_order.order_date
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_order.update_datetime
     *
     * @return the value of t_course_order.update_datetime
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    public Date getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_order.update_datetime
     *
     * @param updateDatetime the value for t_course_order.update_datetime
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    public void setUpdateDatetime(Date updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_order.name
     *
     * @return the value of t_course_order.name
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_order.name
     *
     * @param name the value for t_course_order.name
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_order.remark
     *
     * @return the value of t_course_order.remark
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_order.remark
     *
     * @param remark the value for t_course_order.remark
     *
     * @mbggenerated Sat Sep 19 23:59:32 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}